- config.toml
- content/_index.md
- content/about.md
- content/resources.md
- content/start.md
- layouts/_default/single.html
- layouts/index.html
- layouts/partials/widget-pinned.html
- layouts/partials/widgets.html
- layouts/taxonomy/archive.html
- layouts/taxonomy/tag.html
- updated hugo with official domain
- added getting started page under /start
- added "pinned posts" widget template
- consolidated widgets to umbrella "widgets.html" template
> Updated to use official domain name

- layouts/_default/list.html
- layouts/index.html
- layouts/partials/header.html
- layouts/partials/widgets.html
- static/css/blog.css
- added template for list bundle pages
- added "Posts" link to top nav
- updated widget order with recent posts above tags section
- added drop shadow styling to text in the hero box (image area)
> Issue#8 - Add missing default `list.html` template

- config.toml
- content/_index.md
- content/about.md
- content/start.md
- layouts/shortcodes/courselink.html
- layouts/shortcodes/meetuplink.html
- layouts/shortcodes/slackjoinrequest.html
- layouts/shortcodes/slacklink.html
- added shortcode for auto-invite slack join request
- updated shortcodes with parameters and default values
> Made copy edits and added slack auto-invite link

- layouts/partials/footer.html
- layouts/partials/header.html
- layouts/partials/widget-pinned.html
- layouts/partials/widget-recent.html
- layouts/partials/widget-tags.html
Now using `relURL` instead of `absURL`.
> Fix #25 - change to relative URLs

- content/about.md
updated group messaged... file was saved to the img folder
> Image update

- content/resources.md
Add Free Code Camp's Medium Python page to the 'Other Notable sites' on the resources page.
> Python articles

- content/resources.md
Update the resources page to make the format of the descriptions to be consistent by capitalizing the first letter in the description.
> Resource Page update

- config.toml
- layouts/partials/footer.html
- added hugo site variable `.Site.LastChange` to footer
- now using copyright info from hugo config
> Added site last mod date to footer

- archetypes/post.md
- content/post/contribute-to-website.md
- content/resources.md
- layouts/partials/widget-toc.html
- layouts/partials/widgets.html
TOC nav is enabled using front matter field
`include_toc: true|false`
> Feature #51 - Added TOC navigation

- content/resources.md
Reorganized page with Python sites section next to Python references.
> Added PyPi link

- layouts/_default/index.rss.xml
- layouts/_default/single.html
- layouts/partials/author-info.html
- layouts/partials/header.html
- added Last updated using page .Lastmod metadata (Git info)
- added RSS link to main index header
- updated RSS info to use last modified dates
> Fix #74 - Add last updated timestamp to page content header

- content/resources.md
Fixed letter case for description of W3 Schools on resources page. Issue #86
> fixed letter-case

- config.toml
Supported emojis:  https://www.webfx.com/tools/emoji-cheat-sheet/
> Enable emoji support!

- content/post/contribute-to-website.md
- content/post/example-unpublished.md
- content/post/how-to-read-in-file-content.md
- content/post/how-to-set-up-virtual-env.md
- added alias urls for quick access to venv how-to:
- `/venv`
- `/virtualenv`
- cleaned up some dates in front matter that were missing quotes
> Added pip instructions to virtual env how-to

- content/next-week-goals.md
- content/resources.md
New branch with updated goal and resource pages, hopefully without conflicts!
> Updated goals and added resource

- content/next-week-goals.md
I updated the goals page for the 21st, added links for Flask-Mega-Tutorial, and Corey Schafer's video series, and a few other small changes.
> Made updates for the 21st meetup

- content/next-week-goals.md
Updated Goals Page for the final meetup of this month. Mentioned Aaron's upcoming CRUD challenge and suggested a tentative timeline for finishing project 1.
> Updated Goals Page

- layouts/partials/footer.html
- layouts/partials/widget-recent.html
- static/css/blog.css
- reversed order of Recent Posts widget so most recent is listed on top
- updated footer link css
> Updated post order, most recent post first

- content/next-week-goals.md
Goals are project 1, Aaron's challenge, and Lecture 4
> Updated Goal's page for the first meetup of June

- content/resources.md
Moved _Flask Mega Tutorial_ to new section
> Added "Web Application Tools" section to Resources with additional links

- content/next-week-goals.md
It's not the same without your contribution, Ethan!
> Updated weekly goals for June 11

- content/post/how-to-set-up-virtual-env.md
- layouts/_default/single.html
- clarified instructions are to be run in terminal
- moved Python check in PATH to troubleshooting section
- refined Hugo page publish date logic to better check `include_date` config
> Updated virtual env instructions

- content/next-week-goals.md
Set the goals as chapters 6 and 7 of the flask tutorial
> updates for 7-2 meetup, chapters 6 and 7

- content/next-week-goals.md
> Updates for Tuesday the 16th Meetup

- content/_index.md
- content/start.md
Left links to Lynda.com but removed copy about that being the current topic of study.
> Added notes about COVID and virtual meetups

- content/_index.md
Just added GCP info to the main page.
> Update _index.md to include GCP info on the index page.
